"""
FIR Draft Generation Service
Generates First Information Report drafts using strict templates.
NO LLM/AI hallucination - purely template-based generation.

Supports:
- English FIR template
- Hindi FIR template (Devanagari)
"""

from typing import Dict, Any, Optional
from datetime import datetime
import uuid

from core.config import settings


class FIRService:
    """
    FIR Draft generation service using strict templates.
    Generates deterministic, structured FIR documents.
    """
    
    def __init__(self):
        """Initialize FIR service with templates."""
        self.english_template = self._get_english_template()
        self.hindi_template = self._get_hindi_template()
    
    def _get_english_template(self) -> str:
        """
        English FIR template following standard format.
        Placeholders use {placeholder_name} format.
        """
        return """
================================================================================
                        FIRST INFORMATION REPORT
                    (Under Section 154 Cr.P.C.)
================================================================================

CASE ID: {case_id}
FIR NO: {fir_number}

--------------------------------------------------------------------------------
1. DISTRICT: {district}                    P.S.: {police_station}
--------------------------------------------------------------------------------

2. DATE & TIME OF OCCURRENCE:
   (a) Date: {incident_date}
   (b) Time: {incident_time}

3. DATE & TIME OF REPORT:
   Date: {report_date}
   Time: {report_time}

4. TYPE OF INFORMATION: {info_type}

--------------------------------------------------------------------------------
                            COMPLAINANT DETAILS
--------------------------------------------------------------------------------

5. NAME OF COMPLAINANT: {complainant_name}

6. ADDRESS: {complainant_address}

7. CONTACT NUMBER: {contact_number}

--------------------------------------------------------------------------------
                           INCIDENT DETAILS
--------------------------------------------------------------------------------

8. PLACE OF OCCURRENCE:
   (a) Direction & Distance from P.S.: {direction_from_ps}
   (b) Address: {incident_location}
   (c) Beat No.: {beat_no}

9. DETAILS OF KNOWN/SUSPECTED/UNKNOWN ACCUSED:
   {accused_details}

10. BRIEF FACTS/DESCRIPTION OF OFFENCE:

{incident_description}

--------------------------------------------------------------------------------
                        PROPERTY STOLEN/INVOLVED
--------------------------------------------------------------------------------

11. PROPERTY DETAILS (if applicable):
{property_details}

--------------------------------------------------------------------------------
                            WITNESS DETAILS
--------------------------------------------------------------------------------

12. WITNESSES (if any):
{witness_details}

--------------------------------------------------------------------------------
                              DECLARATION
--------------------------------------------------------------------------------

I hereby declare that the above information is true and correct to the best
of my knowledge and belief.

Signature of Complainant: ______________________

Date: {signature_date}

--------------------------------------------------------------------------------
                        FOR POLICE USE ONLY
--------------------------------------------------------------------------------

FIR REGISTERED BY: {registering_officer}
RANK: {officer_rank}
STATION: {police_station}

INVESTIGATION OFFICER: ______________________

ACTION TAKEN: Since the above report reveals commission of offence(s), 
registered the case and initiated investigation.

Signature of Officer: ______________________
Date: {registration_date}

================================================================================
                    GENERATED BY CASESYNC - AI FIR SYSTEM
                         {generation_timestamp}
================================================================================
"""
    
    def _get_hindi_template(self) -> str:
        """
        Hindi FIR template in Devanagari script.
        Follows standard Indian FIR format.
        """
        return """
================================================================================
                        प्रथम सूचना रिपोर्ट
                    (धारा 154 दं.प्र.सं. के अंतर्गत)
================================================================================

केस आईडी: {case_id}
एफ.आई.आर. संख्या: {fir_number}

--------------------------------------------------------------------------------
1. जिला: {district}                    थाना: {police_station}
--------------------------------------------------------------------------------

2. घटना की तिथि एवं समय:
   (क) तिथि: {incident_date}
   (ख) समय: {incident_time}

3. रिपोर्ट की तिथि एवं समय:
   तिथि: {report_date}
   समय: {report_time}

4. सूचना का प्रकार: {info_type}

--------------------------------------------------------------------------------
                            शिकायतकर्ता का विवरण
--------------------------------------------------------------------------------

5. शिकायतकर्ता का नाम: {complainant_name}

6. पता: {complainant_address}

7. संपर्क नंबर: {contact_number}

--------------------------------------------------------------------------------
                            घटना का विवरण
--------------------------------------------------------------------------------

8. घटना स्थल:
   (क) थाने से दिशा एवं दूरी: {direction_from_ps}
   (ख) पता: {incident_location}
   (ग) बीट नंबर: {beat_no}

9. ज्ञात/संदिग्ध/अज्ञात अभियुक्त का विवरण:
   {accused_details}

10. अपराध का संक्षिप्त विवरण:

{incident_description}

--------------------------------------------------------------------------------
                    चोरी/संबंधित संपत्ति का विवरण
--------------------------------------------------------------------------------

11. संपत्ति का विवरण (यदि लागू हो):
{property_details}

--------------------------------------------------------------------------------
                            गवाहों का विवरण
--------------------------------------------------------------------------------

12. गवाह (यदि कोई हो):
{witness_details}

--------------------------------------------------------------------------------
                              घोषणा
--------------------------------------------------------------------------------

मैं घोषणा करता/करती हूं कि उपरोक्त जानकारी मेरी जानकारी और विश्वास के
अनुसार सत्य और सही है।

शिकायतकर्ता के हस्ताक्षर: ______________________

तिथि: {signature_date}

--------------------------------------------------------------------------------
                        केवल पुलिस उपयोग हेतु
--------------------------------------------------------------------------------

एफ.आई.आर. पंजीकरणकर्ता: {registering_officer}
पद: {officer_rank}
थाना: {police_station}

जांच अधिकारी: ______________________

की गई कार्रवाई: चूंकि उपरोक्त रिपोर्ट से अपराध का खुलासा होता है,
मामला दर्ज किया गया और जांच शुरू की गई।

अधिकारी के हस्ताक्षर: ______________________
तिथि: {registration_date}

================================================================================
                    केससिंक द्वारा निर्मित - एआई एफआईआर प्रणाली
                         {generation_timestamp}
================================================================================
"""
    
    def generate_fir_draft(
        self,
        case_id: str,
        entities: Dict[str, Any],
        language: str,
        additional_info: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate FIR draft from extracted entities.
        
        Args:
            case_id: Unique case identifier
            entities: Extracted entities from NER service
            language: Language code ('hi' or 'en')
            additional_info: Optional additional information
            
        Returns:
            str: Formatted FIR draft content
        """
        # Select template based on language
        template = self.hindi_template if language == 'hi' else self.english_template
        
        # Extract entity values with defaults
        person_names = entities.get('person_names', [])
        locations = entities.get('locations', [])
        dates = entities.get('dates', [])
        incident = entities.get('incident', '')
        
        # Prepare template values
        additional_info = additional_info or {}
        now = datetime.now()
        
        # Determine complainant name (first person name or default)
        complainant_name = person_names[0] if person_names else self._get_default('unknown_person', language)
        
        # Determine incident location (first location or default)
        incident_location = locations[0] if locations else self._get_default('unknown_location', language)
        
        # Determine incident date (first date or default to today)
        incident_date = dates[0] if dates else now.strftime('%d-%m-%Y')
        incident_time = ''
        if len(dates) > 1:
            # Check if second entry looks like time
            for d in dates[1:]:
                if ':' in d or any(x in d.lower() for x in ['am', 'pm', 'बजे']):
                    incident_time = d
                    break
        if not incident_time:
            incident_time = self._get_default('unknown_time', language)
        
        # Build property details from incident text
        property_details = self._extract_property_details(incident, language)
        
        # Build accused details (unknown for most cases from transcript)
        accused_details = self._get_default('unknown_accused', language)
        
        # Build witness details
        witness_details = self._get_default('witness_pending', language)
        
        # Format values dict
        values = {
            'case_id': str(case_id)[:8].upper(),
            'fir_number': f"FIR/{now.year}/{str(uuid.uuid4())[:6].upper()}",
            'district': additional_info.get('district', 'Gurugram'),
            'police_station': additional_info.get('police_station', 'Central Police Station' if language == 'en' else 'केंद्रीय थाना'),
            'incident_date': incident_date,
            'incident_time': incident_time,
            'report_date': now.strftime('%d-%m-%Y'),
            'report_time': now.strftime('%H:%M'),
            'info_type': 'Written' if language == 'en' else 'लिखित',
            'complainant_name': complainant_name,
            'complainant_address': self._find_address(locations, incident, language),
            'contact_number': self._extract_phone(incident) or self._get_default('not_provided', language),
            'direction_from_ps': self._get_default('within_jurisdiction', language),
            'incident_location': incident_location,
            'beat_no': '-',
            'accused_details': accused_details,
            'incident_description': incident or self._get_default('incident_pending', language),
            'property_details': property_details,
            'witness_details': witness_details,
            'signature_date': now.strftime('%d-%m-%Y'),
            'registering_officer': self._get_default('duty_officer', language),
            'officer_rank': self._get_default('si_rank', language),
            'registration_date': now.strftime('%d-%m-%Y'),
            'generation_timestamp': now.strftime('%Y-%m-%d %H:%M:%S')
        }
        
        # Fill template
        try:
            fir_content = template.format(**values)
        except KeyError as e:
            # Handle missing placeholders gracefully
            print(f"Warning: Missing template placeholder: {e}")
            fir_content = template
            for key, value in values.items():
                fir_content = fir_content.replace('{' + key + '}', str(value))
        
        return fir_content
    
    def _get_default(self, key: str, language: str) -> str:
        """Get default text based on language."""
        defaults = {
            'unknown_person': {
                'en': '[Name to be filled]',
                'hi': '[नाम भरा जाना है]'
            },
            'unknown_location': {
                'en': '[Location to be filled]',
                'hi': '[स्थान भरा जाना है]'
            },
            'unknown_time': {
                'en': '[Time not specified]',
                'hi': '[समय निर्दिष्ट नहीं]'
            },
            'unknown_accused': {
                'en': 'Unknown persons (to be identified during investigation)',
                'hi': 'अज्ञात व्यक्ति (जांच के दौरान पहचाना जाना है)'
            },
            'witness_pending': {
                'en': 'Witness details to be recorded during investigation',
                'hi': 'जांच के दौरान गवाहों का विवरण दर्ज किया जाएगा'
            },
            'incident_pending': {
                'en': '[Incident details to be filled]',
                'hi': '[घटना विवरण भरा जाना है]'
            },
            'not_provided': {
                'en': 'Not provided',
                'hi': 'प्रदान नहीं किया गया'
            },
            'within_jurisdiction': {
                'en': 'Within P.S. jurisdiction',
                'hi': 'थाना क्षेत्राधिकार में'
            },
            'duty_officer': {
                'en': 'Duty Officer',
                'hi': 'ड्यूटी अधिकारी'
            },
            'si_rank': {
                'en': 'Sub-Inspector',
                'hi': 'उप-निरीक्षक'
            },
            'no_property': {
                'en': 'No property details mentioned',
                'hi': 'कोई संपत्ति विवरण उल्लेखित नहीं'
            }
        }
        
        return defaults.get(key, {}).get(language, defaults.get(key, {}).get('en', '[N/A]'))
    
    def _find_address(self, locations: list, incident: str, language: str) -> str:
        """Extract address from locations and incident text."""
        # Look for address patterns
        address_parts = []
        
        for loc in locations:
            loc_lower = loc.lower()
            # Include if looks like address
            if any(x in loc_lower for x in ['house', 'sector', 'colony', 'nagar', 'road', 'मकान', 'सेक्टर']):
                address_parts.append(loc)
        
        if address_parts:
            return ', '.join(address_parts[:3])
        
        # Return first few locations as address
        if locations:
            return ', '.join(locations[:2])
        
        return self._get_default('unknown_location', language)
    
    def _extract_phone(self, text: str) -> Optional[str]:
        """Extract phone number from text."""
        import re
        # Indian phone number patterns
        patterns = [
            r'\b(\d{10})\b',  # 10 digit
            r'\b(\d{5}\s*\d{5})\b',  # 5+5 digit
            r'\+91[\s-]*(\d{10})\b',  # With country code
        ]
        
        for pattern in patterns:
            match = re.search(pattern, text)
            if match:
                return match.group(1).replace(' ', '')
        
        return None
    
    def _extract_property_details(self, incident: str, language: str) -> str:
        """Extract property/stolen items details from incident text."""
        import re
        
        property_items = []
        
        # English patterns
        en_patterns = [
            r'(mobile phone[^,.\n]*)',
            r'(wallet[^,.\n]*)',
            r'(phone[^,.\n]*Samsung[^,.\n]*)',
            r'(Rs\.?\s*\d+[^,.\n]*)',
            r'(₹\s*\d+[^,.\n]*)',
            r'(\d+\s*rupees[^,.\n]*)',
            r'(Aadhaar card)',
            r'(PAN card)',
            r'(gold[^,.\n]*)',
            r'(jewelry[^,.\n]*)',
            r'(laptop[^,.\n]*)',
            r'(cash[^,.\n]*)',
        ]
        
        # Hindi patterns
        hi_patterns = [
            r'(मोबाइल फोन[^,।\n]*)',
            r'(बटुआ[^,।\n]*)',
            r'(रुपये[^,।\n]*)',
            r'(₹\s*\d+[^,।\n]*)',
            r'(आधार कार्ड)',
            r'(सोना[^,।\n]*)',
            r'(आभूषण[^,।\n]*)',
            r'(नकद[^,।\n]*)',
        ]
        
        patterns = hi_patterns if language == 'hi' else en_patterns
        
        for pattern in patterns:
            matches = re.findall(pattern, incident, re.IGNORECASE)
            for match in matches:
                if match and match not in property_items:
                    property_items.append(match.strip())
        
        if property_items:
            return '\n   - ' + '\n   - '.join(property_items[:5])
        
        return self._get_default('no_property', language)


# Singleton instance
fir_service = FIRService()
